---
- hosts: all
  become: true
  tasks:
  - name: Install apache2
    apt:
      name: apache2
  - name: start apache on boot
    service:
      name: apache2
      state: started
      enabled: true

